// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1iQhHPPbcmkrZtVKVA9uWvRGOwiQf4Lc',
    appId: '1:589830493887:web:feeabe87d774541ad1580a',
    messagingSenderId: '589830493887',
    projectId: 'flutter-turism',
    authDomain: 'flutter-turism.firebaseapp.com',
    storageBucket: 'flutter-turism.firebasestorage.app',
    measurementId: 'G-F3RHEES0VF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0PojrbFVVXzbCmjk0TkM6MncCEKMaHnQ',
    appId: '1:589830493887:android:f5a555e210338ff5d1580a',
    messagingSenderId: '589830493887',
    projectId: 'flutter-turism',
    storageBucket: 'flutter-turism.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAGl3_713Vjpl-dS-H9N3MjHjSW03OjuE',
    appId: '1:589830493887:ios:aba4755c50fcb773d1580a',
    messagingSenderId: '589830493887',
    projectId: 'flutter-turism',
    storageBucket: 'flutter-turism.firebasestorage.app',
    iosBundleId: 'com.example.flutterTurism',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAGl3_713Vjpl-dS-H9N3MjHjSW03OjuE',
    appId: '1:589830493887:ios:aba4755c50fcb773d1580a',
    messagingSenderId: '589830493887',
    projectId: 'flutter-turism',
    storageBucket: 'flutter-turism.firebasestorage.app',
    iosBundleId: 'com.example.flutterTurism',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1iQhHPPbcmkrZtVKVA9uWvRGOwiQf4Lc',
    appId: '1:589830493887:web:66dc18abcf2deafad1580a',
    messagingSenderId: '589830493887',
    projectId: 'flutter-turism',
    authDomain: 'flutter-turism.firebaseapp.com',
    storageBucket: 'flutter-turism.firebasestorage.app',
    measurementId: 'G-C2TBG4PQ6F',
  );

}